# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jetson.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cjetson.proto\x12\x10JetsonParameters\"\x14\n\x12TemperatureRequest\")\n\x13TemperatureResponse\x12\x12\n\nparameters\x18\x01 \x01(\t2{\n\x17JetsonProcessingService\x12`\n\x11JetsonTemperature\x12$.JetsonParameters.TemperatureRequest\x1a%.JetsonParameters.TemperatureResponseB\x0f\xaa\x02\x0cJetsonProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jetson_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014JetsonProtos'
  _globals['_TEMPERATUREREQUEST']._serialized_start=34
  _globals['_TEMPERATUREREQUEST']._serialized_end=54
  _globals['_TEMPERATURERESPONSE']._serialized_start=56
  _globals['_TEMPERATURERESPONSE']._serialized_end=97
  _globals['_JETSONPROCESSINGSERVICE']._serialized_start=99
  _globals['_JETSONPROCESSINGSERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
