# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gRPC_stream import NDD_API_pb2 as gRPC__stream_dot_NDD__API__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gRPC_stream/NDD_API_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DataProcessingServiceStub(object):
    """Сервис обработки данных
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProceedDataStream = channel.unary_stream(
                '/NeuroDataProcessing.DataProcessingService/ProceedDataStream',
                request_serializer=gRPC__stream_dot_NDD__API__pb2.VoidRequest.SerializeToString,
                response_deserializer=gRPC__stream_dot_NDD__API__pb2.DataResponse.FromString,
                _registered_method=True)


class DataProcessingServiceServicer(object):
    """Сервис обработки данных
    """

    def ProceedDataStream(self, request, context):
        """RPC для отправки данных
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProceedDataStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ProceedDataStream,
                    request_deserializer=gRPC__stream_dot_NDD__API__pb2.VoidRequest.FromString,
                    response_serializer=gRPC__stream_dot_NDD__API__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NeuroDataProcessing.DataProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('NeuroDataProcessing.DataProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataProcessingService(object):
    """Сервис обработки данных
    """

    @staticmethod
    def ProceedDataStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/NeuroDataProcessing.DataProcessingService/ProceedDataStream',
            gRPC__stream_dot_NDD__API__pb2.VoidRequest.SerializeToString,
            gRPC__stream_dot_NDD__API__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
