# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolov5/gRPC_stream/with_central_freq_and_img/neuro.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8yolov5/gRPC_stream/with_central_freq_and_img/neuro.proto\x12\x13NeuroDataProcessing\"V\n\tUavObject\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.NeuroDataProcessing.DroneType\x12\r\n\x05state\x18\x02 \x01(\x08\x12\x0c\n\x04\x66req\x18\x03 \x01(\x05\"e\n\x0c\x44\x61taResponse\x12\'\n\x04\x62\x61nd\x18\x01 \x01(\x0e\x32\x19.NeuroDataProcessing.Band\x12,\n\x04uavs\x18\x02 \x03(\x0b\x32\x1e.NeuroDataProcessing.UavObject\"\r\n\x0bVoidRequest\"e\n\rImageResponse\x12\'\n\x04\x62\x61nd\x18\x01 \x01(\x0e\x32\x19.NeuroDataProcessing.Band\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\"7\n\x0cImageRequest\x12\'\n\x04\x62\x61nd\x18\x01 \x01(\x0e\x32\x19.NeuroDataProcessing.Band*2\n\tDroneType\x12\t\n\x05\x41utel\x10\x00\x12\x07\n\x03\x46pv\x10\x01\x12\x07\n\x03\x44ji\x10\x02\x12\x08\n\x04Wifi\x10\x03* \n\x04\x42\x61nd\x12\x0b\n\x07\x42\x61nd2p4\x10\x00\x12\x0b\n\x07\x42\x61nd5p8\x10\x01\x32\xd6\x01\n\x15\x44\x61taProcessingService\x12Z\n\x11ProceedDataStream\x12 .NeuroDataProcessing.VoidRequest\x1a!.NeuroDataProcessing.DataResponse0\x01\x12\x61\n\x16SpectrogramImageStream\x12!.NeuroDataProcessing.ImageRequest\x1a\".NeuroDataProcessing.ImageResponse0\x01\x42\x0e\xaa\x02\x0bNeuroProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolov5.gRPC_stream.with_central_freq_and_img.neuro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\013NeuroProtos'
  _globals['_DRONETYPE']._serialized_start=447
  _globals['_DRONETYPE']._serialized_end=497
  _globals['_BAND']._serialized_start=499
  _globals['_BAND']._serialized_end=531
  _globals['_UAVOBJECT']._serialized_start=81
  _globals['_UAVOBJECT']._serialized_end=167
  _globals['_DATARESPONSE']._serialized_start=169
  _globals['_DATARESPONSE']._serialized_end=270
  _globals['_VOIDREQUEST']._serialized_start=272
  _globals['_VOIDREQUEST']._serialized_end=285
  _globals['_IMAGERESPONSE']._serialized_start=287
  _globals['_IMAGERESPONSE']._serialized_end=388
  _globals['_IMAGEREQUEST']._serialized_start=390
  _globals['_IMAGEREQUEST']._serialized_end=445
  _globals['_DATAPROCESSINGSERVICE']._serialized_start=534
  _globals['_DATAPROCESSINGSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
