connections:
  2G437:
    ip: 192.168.1.3
    port: 16024
    signal_settings:
      signal_width: 2048
      signal_height: 3072
      sample_rate: 245760000
      calculate_log: false
    neural_network_settings:
      project_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5
      weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver3\weights\best.pt
      img_size:
      - 640
      - 640
      z_min: -78
      z_max: 72
    detection_settings:
      all_classes:
      - dji
      - wifi
      - autel_lite
      - autel_max_4n(t)
      - autel_tag
      - fpv
      map_list:
      - autel
      - fpv
      - dji
      - wifi
      accumulation_size: 10
      threshold: 0.4
      exceedance: 0.5
  5G7865:
    ip: 192.168.1.3
    port: 16058
    signal_settings:
      signal_width: 2048
      signal_height: 3072
      sample_rate: 245760000
      calculate_log: false
    neural_network_settings:
      project_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5
      weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver3\weights\best.pt
      img_size:
      - 640
      - 640
      z_min: -78
      z_max: 69
    detection_settings:
      all_classes:
      - dji
      - wifi
      - autel_lite
      - autel_max_4n(t)
      - autel_tag
      - fpv
      map_list:
      - autel
      - fpv
      - dji
      - wifi
      accumulation_size: 10
      threshold: 0.4
      exceedance: 0.5
