connections:
  2G437_Alinx:
    ip: 192.168.1.3
    port: 16024
    hardware_type: Alinx
    signal_settings:
      signal_width: 1024
      signal_height: 3072
      sample_rate: 12880000
      calculate_log: false
    neural_network_settings:
      project_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5
      weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver4\weights\best.pt
      img_size:
      - 640
      - 640
      z_min: -22
      z_max: 120
    detection_settings:
      all_classes:
      - dji
      - wifi
      - autel_lite
      - autel_max_4n(t)
      - autel_tag
      - fpv
      map_list:
      - autel
      - fpv
      - dji
      - wifi
      accumulation_size: 15
      threshold: 0.7
      exceedance: 0.5
  5G7865_Alinx:
    ip: 192.168.1.3
    port: 16058
    hardware_type: Alinx
    signal_settings:
      signal_width: 1024
      signal_height: 3072
      sample_rate: 12880000
      calculate_log: false
    neural_network_settings:
      project_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5
      weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver4\weights\best.pt
      img_size:
      - 640
      - 640
      z_min: -22
      z_max: 120
    detection_settings:
      all_classes:
      - dji
      - wifi
      - autel_lite
      - autel_max_4n(t)
      - autel_tag
      - fpv
      map_list:
      - autel
      - fpv
      - dji
      - wifi
      accumulation_size: 15
      threshold: 0.6000000000000001
      exceedance: 0.5
  2G437_USRP:
    ip: 127.0.0.1
    port: 10091
    hardware_type: USRP
    signal_settings:
      signal_width: 1024
      signal_height: 2048
      sample_rate: 80000000
      calculate_log: false
    neural_network_settings:
      project_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5
      weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver3\weights\best.pt
      img_size:
      - 640
      - 640
      z_min: -60
      z_max: 75
    detection_settings:
      all_classes:
      - dji
      - wifi
      - autel_lite
      - autel_max_4n(t)
      - autel_tag
      - fpv
      map_list:
      - autel
      - fpv
      - dji
      - wifi
      accumulation_size: 10
      threshold: 0.4
      exceedance: 0.5
  1G4_USRP:
    ip: 127.0.0.1
    port: 10092
    hardware_type: USRP
    signal_settings:
      signal_width: 1024
      signal_height: 2048
      sample_rate: 80000000
      calculate_log: false
    neural_network_settings:
      project_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5
      weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver3\weights\best.pt
      img_size:
      - 640
      - 640
      z_min: -60
      z_max: 75
    detection_settings:
      all_classes:
      - dji
      - wifi
      - autel_lite
      - autel_max_4n(t)
      - autel_tag
      - fpv
      map_list:
      - autel
      - fpv
      - dji
      - wifi
      accumulation_size: 10
      threshold: 0.4
      exceedance: 0.5
  5G8_USRP:
    ip: 127.0.0.1
    port: 10093
    hardware_type: USRP
    signal_settings:
      signal_width: 1024
      signal_height: 2048
      sample_rate: 80000000
      calculate_log: false
    neural_network_settings:
      project_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5
      weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver3\weights\best.pt
      img_size:
      - 640
      - 640
      z_min: -40
      z_max: 40
    detection_settings:
      all_classes:
      - dji
      - wifi
      - autel_lite
      - autel_max_4n(t)
      - autel_tag
      - fpv
      map_list:
      - autel
      - fpv
      - dji
      - wifi
      accumulation_size: 10
      threshold: 0.4
      exceedance: 0.5
  5G2_USRP:
    ip: 127.0.0.1
    port: 10094
    hardware_type: USRP
    signal_settings:
      signal_width: 1024
      signal_height: 2048
      sample_rate: 80000000
      calculate_log: false
    neural_network_settings:
      project_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5
      weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver3\weights\best.pt
      img_size:
      - 640
      - 640
      z_min: -40
      z_max: 40
    detection_settings:
      all_classes:
      - dji
      - wifi
      - autel_lite
      - autel_max_4n(t)
      - autel_tag
      - fpv
      map_list:
      - autel
      - fpv
      - dji
      - wifi
      accumulation_size: 10
      threshold: 0.4
      exceedance: 0.5
