h = 3072            # 2048 or 3072
w = 1024
msg_len = h*w*4+16
all_classes = ['dji', 'wifi', 'autel_lite', 'autel_max_4n(t)', 'autel_tag', 'fpv', '3G/4G']
map_list = ['noise', 'autel', 'fpv', 'dji', 'wifi', '3G/4G']
project_path = r"C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5"
weights_path = r"C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_aftertrain_2\weights\best.pt"
save_path = None
save_result_path = None
RETURN_MODE = None         # None or "CUSTOM" or 'tcp'
IMG_SIZE = (640, 640)
FREQ_SMPLS = 122880000