connections:
- name: 2G4
  weights_path: C:/Users/v.stecko/Desktop/YOLOv5 Project/yolov5/runs/train/yolov5m_6classes_AUGMENTATED_3/weights/best.pt
  ip: 192.168.1.3
  port: 16024
- name: 5G8
  weights_path: C:/Users/v.stecko/Desktop/YOLOv5 Project/yolov5/runs/train/yolov5m_6classes_AUGMENTATED_3/weights/best.pt
  ip: 192.168.1.3
  port: 16058
