connections:
- name: '1CH'
  ip: 127.0.0.1
  port: 10091
  weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver2\weights\best.pt
  img_size: (640, 640)
  map_list: ['noise', 'autel', 'fpv', 'dji', 'wifi']
  all_classes: ['dji', 'wifi', 'autel_lite', 'autel_max_4n(t)', 'autel_tag', 'fpv', '3G/4G']
  hardware_type: 'twinrx'
  z_scale: [-40, 40]

- name: '2CH'
  ip: 127.0.0.1
  port: 10092
  weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver2\weights\best.pt
  img_size: (640, 640)
  map_list: ['noise', 'autel', 'fpv', 'dji', 'wifi']

  all_classes: ['dji', 'wifi', 'autel_lite', 'autel_max_4n(t)', 'autel_tag', 'fpv', '3G/4G']
  hardware_type: 'twinrx'
  z_scale: [-40, 40]

- name: '3CH'
  ip: 127.0.0.1
  port: 10093
  weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver2\weights\best.pt
  img_size: (640, 640)
  map_list: ['noise', 'autel', 'fpv', 'dji', 'wifi']
  all_classes: ['dji', 'wifi', 'autel_lite', 'autel_max_4n(t)', 'autel_tag', 'fpv', '3G/4G']
  hardware_type: 'twinrx'
  z_scale: [-40, 40]

- name: '4CH'
  ip: 127.0.0.1
  port: 10094
  weights_path: C:\Users\v.stecko\Desktop\YOLOv5 Project\yolov5\runs\train\yolov5m_6classes_BIG_AUGMENTATED_ver2\weights\best.pt
  img_size: (640, 640)
  map_list: ['noise', 'autel', 'fpv', 'dji', 'wifi']
  all_classes: ['dji', 'wifi', 'autel_lite', 'autel_max_4n(t)', 'autel_tag', 'fpv', '3G/4G']
  hardware_type: 'twinrx'
  z_scale: [-40, 40]



