connections:
- name: 7cl (16024)
  weights_path: C:/Users/v.stecko/Desktop/YOLOv5 Project/yolov5/runs/train/yolov5m_6classes_AUGMENTATED_2/weights/best.pt
  ip: 192.168.1.3
  port: 16024
- name: 6cl (16058)
  weights_path: C:/Users/v.stecko/Desktop/YOLOv5 Project/yolov5/runs/train/yolov5m_6classes_AUGMENTATED_2/weights/best.pt
  ip: 192.168.1.3
  port: 16058
