connections:
- name: ''
  weights_path: C:/Users/v.stecko/Desktop/YOLOv5 Project/yolov5/runs/train/yolov5m_6classes_aftertrain_2/weights/best.pt
  ip: 127.0.0.1
  port: 10091
- name: ''
  weights_path: C:/Users/v.stecko/Desktop/YOLOv5 Project/yolov5/runs/train/yolov5m_6classes_aftertrain_2/weights/best.pt
  ip: 127.0.0.1
  port: 10092
- name: ''
  weights_path: C:/Users/v.stecko/Desktop/YOLOv5 Project/yolov5/runs/train/yolov5m_6classes_aftertrain_2/weights/best.pt
  ip: 127.0.0.1
  port: 10093
- name: ''
  weights_path: C:/Users/v.stecko/Desktop/YOLOv5 Project/yolov5/runs/train/yolov5m_6classes_aftertrain_2/weights/best.pt
  ip: 127.0.0.1
  port: 10094
