# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: define_API.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x65\x66ine_API.proto\x12\x0e\x64\x61taProcessing\"A\n\x06Result\x12(\n\x04type\x18\x01 \x01(\x0e\x32\x1a.dataProcessing.DroneTypes\x12\r\n\x05state\x18\x02 \x01(\x08\"D\n\x0b\x44\x61taRequest\x12\x0c\n\x04\x62\x61nd\x18\x01 \x01(\x05\x12\'\n\x07results\x18\x03 \x03(\x0b\x32\x16.dataProcessing.Result\"\x1f\n\x0c\x44\x61taResponse\x12\x0f\n\x07message\x18\x01 \x01(\t*3\n\nDroneTypes\x12\t\n\x05\x61utel\x10\x00\x12\x07\n\x03\x66pv\x10\x01\x12\x07\n\x03\x64ji\x10\x02\x12\x08\n\x04wifi\x10\x03\x32^\n\x15\x44\x61taProcessingService\x12\x45\n\x08SendData\x12\x1b.dataProcessing.DataRequest\x1a\x1c.dataProcessing.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'define_API_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRONETYPES']._serialized_start=206
  _globals['_DRONETYPES']._serialized_end=257
  _globals['_RESULT']._serialized_start=36
  _globals['_RESULT']._serialized_end=101
  _globals['_DATAREQUEST']._serialized_start=103
  _globals['_DATAREQUEST']._serialized_end=171
  _globals['_DATARESPONSE']._serialized_start=173
  _globals['_DATARESPONSE']._serialized_end=204
  _globals['_DATAPROCESSINGSERVICE']._serialized_start=259
  _globals['_DATAPROCESSINGSERVICE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
